//isDummyBuild=false
//mcVersion="1.7.10"
//modVersion="1.1"
//modGroup="com.gamerforea.eventhelper"
//modId="eventhelper"
//modName="Event Helper"
//modArchivesName="EventHelper"
//modAuthor=arrayOf("gameforea", "Veritaris", "Aizistral")
//modIcon="EH_logo.png"
//modDescription="Bukkit integration for Forge mods."
//modCredits="gameforea"